### ISSUE TITLE
strdistance installation and StataJavaUtilities binary

### ISSUE THREAD

**Issue by MatthewLGibbons** [wbuchanan/StataStringUtilities#6]
I've installed the net inst strutil code and tried the demonstration program. However, I got the below result. I'm using Stata 15 over a remote server. W Buchanan has stated: "Looks like you need the StataJavaUtilities binary as well". More details at some point about what I need to install would be helpful. 

strdist state state2, coss(cosine_sim) cosd(cosine_dist) damerau(dam) jaccards(jaccard_sim) jaccardd(jaccard_dist)

java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Nativ e Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Native MethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(De legatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.stata.Javacall.load(Javacall.java:132)
at com.stata.Javacall.load(Javacall.java:92)
Caused by: java.lang.NoClassDefFoundError: org/paces/Stata/MetaData/Meta
at org.paces.Stata.StringUtils.Similarity.DistanceMet rics.<init>(DistanceMetrics.java:169)
at org.paces.Stata.StringUtils.StringUtilities.distan ce(StringUtilities.java:53)
... 6 more
r(5100);

**Comment by wbuchanan** [comment]
@MatthewLGibbons 
The shortest answer is that you need to download the [StataJavaUtilities](https://github.com/wbuchanan/StataJavaUtilities/blob/master/target/StataJavaUtilities.jar) binary (the link to the left will get you directly to the binary) and include it on the `adopath` in Stata.  If the link won't let you download the binary, you can go to the [StataJavaUtilities repository](https://github.com/wbuchanan/StataJavaUtilities) and then you'll want to get a copy of the StataJavaUtilities.jar file from the target subdirectory.  

`org/paces/Stata/MetaData/Meta` or `org.paces.Stata.MetaData.Meta` is one of the Java classes that I use to access all of the data and is basically the first step in the process of accessing the data through that class (e.g., it constructs all of the metadata that might be needed to consistently access the data and is passed as an argument to the `DataSet` and `DataRecord` classes.

**Comment by wbuchanan** [comment]
@MatthewLGibbons 
Did the previous information help with regards to getting things up and running?

**Comment by MatthewLGibbons** [comment]
Hi William,

I downloaded StataJavaUtilities.jar and added it to C:\ado\plus. However,
when I try use "C:\ado\plus\+
StataJavaUtilities/target/StataJavaUtilities.jar" and variations on this I
get:
file C:\ado\plus\+ StataJavaUtilities/target/StataJavaUtilities.jar not
found.

I've never set up an adopath before, but will have another go tomorrow and
get some advice on Java.

Thanks for your interest.

Matthew

**Comment by wbuchanan** [comment]
@MatthewLGibbons
One that file is on the `adopath` you shouldn’t have to do anything else.  It is basically putting those classes in a location where the Java Virtual Machine that Stata uses will find it.

**Comment by cpmasesa** [comment]
Hi William, 

Landed here as I look for a solution to using your utility.

Despite putting the .jar in adopath I still get an error message (attached image)  when I try to call strdist.

Can you please advise what I need to do to get this working? I'm using STATA/IC 15.1 on a 64 bit Windows 10 computer.

Clemens
![strdist_error](https://user-images.githubusercontent.com/11004122/92437368-07bed200-f1a7-11ea-86fa-056bba4ffccb.PNG)

**Comment by cpmasesa** [comment]
> Hi William,
> 
> Landed here as I look for a solution to using your utility.
> 
> Despite putting the .jar in adopath I still get an error message (attached image) when I try to call strdist.
> 
> Can you please advise what I need to do to get this working? I'm using STATA/IC 15.1 on a 64 bit Windows 10 computer.
> 
> Clemens
> ![strdist_error](https://user-images.githubusercontent.com/11004122/92437368-07bed200-f1a7-11ea-86fa-056bba4ffccb.PNG)

I figured out the issue I had and it's now working fine.

Clemens

**Comment by wbuchanan** [comment]
@cpmasesa 
Did you also install the StataJavaUtilities binary?  org/paces/Stata/MetaData/Meta is a class from that library which is a dependency of several other programs I've written that use Java.

**Comment by cpmasesa** [comment]
Yes, I followed so the steps. I sorted the problem I had but restarting STATA.

I’m now sorted, thanks.

Clemens

**Comment by wbuchanan** [comment]
@cpmasesa 
It may have been related to the JVM already being started, although I believe the Java API as of Stata 16 updated the way that the classpath works to prevent locking it.

**Comment by kotsenko** [comment]
I think I am also having an issue related to StataJavaUtilities installation with Stata17
"github install wbuchanan/StataStringUtilities" was successful
"phoneticenc projectname, caverphone1(cav1)" results in "java.lang.ClassNotFoundException: org.paces.Stata.MetaData.Meta ... at com.stata.Javacall.load(Javacall.java:92)"
thought I should install StataJavaUtilities but
"github install wbuchanan/StataJavaUtilities" results in " https://raw.githubusercontent.com/wbuchanan/statajavautilities/master/stata.toc not found "
