### ISSUE TITLE
phoneticenc ... dblm() with missingness fails in Stata 16

### ISSUE THREAD

**Issue by aalexandersson** [wbuchanan/StataStringUtilities#7]
`phoneticenc `works in Stata 15 but fails in Stata 16. I am using Stata/MP for Windows (64-bit x86-64):

```
clear
input str15 last_name
"shadbolt"
""        
"ayres"   
"campbell"
"parmakli"
end

phoneticenc last_name, dblmetaphone(dblml)
```

The error in Stata 16 is 

```
java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknow
> n Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.stata.Javacall.load(Javacall.java:130)
        at com.stata.Javacall.load(Javacall.java:90)
Caused by: java.lang.NullPointerException
r(5100);
```

The error is caused by the missingness. For example, this code works in both Stata 15 and 16:

```
clear
input str15 last_name
"shadbolt"
"hello"        
"ayres"   
"campbell"
"parmakli"
end

phoneticenc last_name, dblmetaphone(dblml)
```

I am unable to fix the problem under version control. Basically, I want to use Stata 16 but if I do then I can no longer use your program because of the error. Please advice. I can cross-post on Statalist if you would like.

**Comment by wbuchanan** [comment]
@aalexandersson 
I hadn't thought about this previously.  It may take me a bit to get around to patching this bug, but feel free to bug me in the meantime.  As one quick thought for a potential work around have you tried this in Stata 16:

```
clear
input str15 last_name
"shadbolt"
""        
"ayres"   
"campbell"
"parmakli"
end

phoneticenc last_name if !mi(last_name), dblmetaphone(dblml)
```

It's been quite a while since I've last looked at this code so I'm not sure whether or not I included an if option in the command.  If I did, I think this might help work around the issue in the meantime.

**Comment by aalexandersson** [comment]
Thanks, adding the if qualifier works well enough! Should have thought about it myself. You can close the issue.

**Comment by wbuchanan** [comment]
@aalexandersson 
I'm actually going to leave the issue open until I fix the underlying issue.  Your response was very reasonable (e.g., calling the command should not produce and error when the data are strings) and the program should handle cases with missing string data appropriately.  That said, I'm glad that we found a work around for your issue fairly quickly/easily.
